networks:
  nw:
    driver: bridge

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=2048M
    networks:
      - nw
    ports:
      - 9042:9042
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=2048M
    networks:
      - nw
    depends_on:
      cassandra1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=2048M
    networks:
      - nw
    depends_on:
      cassandra2:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5

#  server_webapp:
#    image: server:latest
#    container_name: server
#    build:
#      context: .
#      dockerfile: Dockerfile
#    networks:
#      - nw
#    ports:
#      - 8080:8080
#    restart: always
#    depends_on:
#      cassandra1:
#        condition: service_healthy
#      cassandra2:
#        condition: service_healthy
#      cassandra3:
#        condition: service_healthy
