networks:
  nw:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    networks:
      - nw
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
#    volumes:
#      - ./spark-shared-data:/opt/bitnami/spark/data/
    networks:
      - nw

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_ADDRESS=spark://spark-master:7077
    depends_on:
      - spark-master
#    volumes:
#      - ./spark-shared-data:/opt/bitnami/spark/data/
    networks:
      - nw

volumes:
  dbdata: