networks:
  nw:
    driver: bridge

services:
  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    restart: always
    volumes:
      - ./config/server.json:/consul/config/server.json:ro
    networks:
      - nw
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bind=0.0.0.0"
