services:
  hazelcast:
    image: hazelcast/hazelcast:latest
    ports:
      - "5701:5701"
    environment:
      - HZ_QUEUE_QUEUE_MAXSIZE=100

  management-center:
    image: hazelcast/management-center:latest
    ports:
      - "8180:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
